
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-app1" 
  namespace: {{ .Values.namespace }}
  labels:
    app: app1
spec:
  replicas: {{ .Values.replicaCount }}  
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
