apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
     app: app1
  ports:
    - port: {{ .Values.port }}
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: {{ .Values.targetPort }}
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: {{ .Values.nodePort }}
