name: "Docker Publish for tags "
on:
  push:
    tags: 
       - "*"
  #workflow_dispatch:
jobs:
 
  build-and-push-with-tags:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
      
    - name: "Login to Docker hub"
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: "Set up QEMU"
      uses: "docker/setup-qemu-action@v3"
    - name: "Set up Docker Buildx"
      uses: "docker/setup-buildx-action@v3"
          
    - name: "Build and push image tags"
      uses: "docker/build-push-action@v6"
      with:
         push: true
         tags: |
           "${{ github.repository }}:${{ github.ref_name }}"

#updating the helm manifests files


  update:
    name: Update Helm Manifests
    runs-on: ubuntu-latest
    needs: build-and-push-with-tags

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        ref: master

    - name: "Get the current branch"
      run: |
        git branch -r

    - name: Update Image Tag Values in values.yaml
      run: |
        chart_dir="helm/project1-chart"
        new_image_tag=${{ github.ref_name }}

        # Update the values.yaml file with the new image tag
        sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"
    
    - name: Commit the changes made
      run: | 
        git config --global init.defaultBranch master
        git config --global user.name 'Abdul Raheem'
        git config --global user.email 'araheemcis@gmail.com'
        git commit -am "updating image tag"
        git push origin master

